version: "3"

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - database
      - migrate
    entrypoint: ["sh", "-c", "go test -cover ./..."]

  database:
    image: postgres
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "password"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgres://test:password@database:5432/test?sslmode=disable",
        "up"
      ]
    depends_on:
      database:
        condition: service_healthy
    restart: on-failure
