version: '3'

services:
  database:
    image: postgres
    environment:
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        POSTGRES_DB: "${POSTGRES_DATABASE}"
        POSTGRES_USER: "${POSTGRES_USER}"
    volumes:
        - db-volume:/var/lib/postgresql/data

  api:
    image: ${IMAGE_NAME}
    environment:
      DATABASE_HOST: database
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DATABASE}"
      POSTGRES_USER: "${POSTGRES_USER}"
    depends_on:
      - database
    ports:
      - "${PORT}:${PORT}"

volumes:
  db-volume:
